export const ADD_NOTE = 'ADD_NOTE'
export const EDIT_NOTE = 'EDIT_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'
export const CLICK_NOTE = 'CLICK_NOTE'
export const FILTER = 'FILTER'
export const START = 'START'
